services:
  mysql:
    image: mysql
    environment:
      MYSQL_USER: "mysql"
      MYSQL_DATABASE: "BPT-DB"
      MYSQL_ROOT_PASSWORD: "GoGoGadgetDatabase!"
      MYSQL_PASSWORD: "GoGoGadgetDatabase!"
    restart: always
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 30
  
  measurement-service:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    restart: always
    ports:
      - 8081:8080
    environment:
      MySQLDbConnection: "Server=mysql;Port=3306;Database=BPT-DB;User=mysql;Password=GoGoGadgetDatabase!"
    depends_on:
      mysql:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
        required: false
  
  patient-service:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    restart: always
    ports:
      - 8082:8080
    environment:
      MySQLDbConnection: "Server=mysql;Port=3306;Database=BPT-DB;User=mysql;Password=GoGoGadgetDatabase!"
    depends_on:
      mysql:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
        required: false
  
  migration-runner:
    build:
      context: Models
      dockerfile: Migration.Dockerfile
    profiles:
      - run-migrations
    environment:
      MySQLDbConnection: "Server=mysql;Port=3306;Database=BPT-DB;User=mysql;Password=GoGoGadgetDatabase!"
    depends_on:
      mysql:
        condition: service_healthy
        
volumes:
  mysqldb: