services:
  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr
  
  mysql:
    image: mysql
    environment:
      MYSQL_USER: "mysql"
      MYSQL_DATABASE: "BPT-DB"
      MYSQL_ROOT_PASSWORD: "GoGoGadgetDatabase!"
  
  measurement-service:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports:
      - 8081:8080
    environment:
      MySQLDbConnection: "Server=localhost;Port=3306;Database=BPT-DB;User=mysql;Password=GoGoGadgetDatabase!"
  
  patient-service:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - 8082:8080
    environment:
      MySQLDbConnection: "Server=localhost;Port=3306;Database=BPT-DB;User=mysql;Password=GoGoGadgetDatabase!"
