services:
  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr
  
  featurehub:
    image: featurehub/party-server:latest
    volumes:
      - featurehub:/db
    ports:
      - 8085:8085