name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - 'Version-1/**'
      - '!Version-1/Models/*.csproj'

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
